import { classNames } from './resources/icons/names.mjs';

/** @type {import('tailwindcss').Config} */
export default {
    content: ['./public/themes/**/renderer.php', `./resources/**/*.{js,css,php,blade.php}`],

    // Rules written into a layer are kept only when something is seen using them, and an icon's
    // class is put together out of a name the server picks — so the templates are searched for
    // spellings that are never written down there. Taken from the stylesheet that declares them,
    // which is the only place the full set exists.
    safelist: classNames(new URL('./', import.meta.url)),
    theme: {
        fontFamily: {
            sans: [
                'system-ui',
                '-apple-system',
                'Segoe UI',
                'Roboto',
                'Helvetica Neue',
                'Arial',
                'Noto Sans',
                'Liberation Sans',
                'sans-serif',
                'Apple Color Emoji',
                'Segoe UI Emoji',
                'Segoe UI Symbol',
                'Noto Color Emoji',
            ],
            mono: [
                'SFMono-Regular',
                'Menlo',
                'Monaco',
                'Consolas',
                'Liberation Mono',
                'Courier New',
                'monospace',
            ],
        },
        extend: {
            screens: {
                '2xl': '100rem',
                '3xl': '120rem',
            },
            boxShadow: {
                sm: '0 1px 2px 0 rgb(var(--shadow-rgb) / 0.05)',
                DEFAULT:
                    '0 1px 3px 0 rgb(var(--shadow-rgb) / 0.1), 0 1px 2px -1px rgb(var(--shadow-rgb) / 0.1)',
                md: '0 4px 6px -1px rgb(var(--shadow-rgb) / 0.1), 0 2px 4px -2px rgb(var(--shadow-rgb) / 0.1)',
                lg: '0 10px 15px -3px rgb(var(--shadow-rgb) / 0.1), 0 4px 6px -4px rgb(var(--shadow-rgb) / 0.1)',
                xl: '0 20px 25px -5px rgb(var(--shadow-rgb) / 0.1), 0 8px 10px -6px rgb(var(--shadow-rgb) / 0.1)',
            },
            dropShadow: {
                DEFAULT: [
                    '0 1px 2px rgb(var(--shadow-rgb) / 0.1)',
                    '0 1px 1px rgb(var(--shadow-rgb) / 0.06)',
                ],
            },
            colors: {
                'header-bg': 'var(--header-bg)',
                'header-txt': 'var(--header-txt)',
                'footer-bg': 'var(--footer-bg)',
                'footer-txt': 'var(--footer-txt)',
                'footer-border': 'var(--footer-border)',
                'table-header-bg': 'var(--table-header-bg)',
                'table-header-txt': 'var(--table-header-txt)',
                'card-header-bg': 'var(--card-header-bg)',
                'card-header-txt': 'var(--card-header-txt)',
                'sidebar-bg': 'var(--sidebar-bg)',
                'sidebar-txt': 'var(--sidebar-txt)',
                'sidebar-border': 'var(--sidebar-border)',
                'logo-mark': 'var(--logo-mark)',
                'logo-accent': 'var(--logo-accent)',
                'breadcrumb-bg': 'var(--breadcrumb-bg)',
                'breadcrumb-txt': 'var(--breadcrumb-txt)',
                'breadcrumb-current-txt': 'var(--breadcrumb-current-txt)',
                'breadcrumb-border': 'var(--breadcrumb-border)',
                'field-border': 'var(--field-border)',
                'field-txt': 'var(--field-txt)',
                'primary-accent': 'var(--primary-accent)',
                'warning-accent': 'var(--warning-accent)',
                'error-accent': 'var(--error-accent)',

                'page-bg': 'var(--page-bg)',
                'page-txt': 'var(--page-txt)',
                // The strip a guest or error page signs off with — host and timestamp — which sits
                // on the page rather than in the app shell, so it is not the footer's to colour.
                'page-caption-bg': 'var(--page-caption-bg)',
                'page-caption-txt': 'var(--page-caption-txt)',

                // Hero (the banded header a guest page — login, logout — sets its title in)
                'hero-bg': 'var(--hero-bg)',
                'hero-title-txt': 'var(--hero-title-txt)',
                'hero-subtitle-txt': 'var(--hero-subtitle-txt)',

                'nav-txt': 'var(--nav-txt)',
                'nav-hover-bg': 'var(--nav-hover-bg)',
                'nav-selected-bg': 'var(--nav-selected-bg)',
                'nav-selected-txt': 'var(--nav-selected-txt)',
                'nav-section-txt': 'var(--nav-section-txt)',
                'nav-guide': 'var(--nav-guide)',
                'nav-caret': 'var(--nav-caret)',
                'nav-caret-hover': 'var(--nav-caret-hover)',
                'nav-icon': 'var(--nav-icon)',
                'nav-icon-hover': 'var(--nav-icon-hover)',
                'nav-disabled-txt': 'var(--nav-disabled-txt)',

                'breadcrumb-separator': 'var(--breadcrumb-separator)',

                'card-bg': 'var(--card-bg)',
                'card-sticky-bg': 'var(--card-sticky-bg)',
                'card-txt': 'var(--card-txt)',
                'card-title-txt': 'var(--card-title-txt)',
                'card-border': 'var(--card-border)',
                'card-divider': 'var(--card-divider)',
                'card-footer-bg': 'var(--card-footer-bg)',
                'card-sunken-bg': 'var(--card-sunken-bg)',
                'card-hover-bg': 'var(--card-hover-bg)',
                'card-row-hover-bg': 'var(--card-row-hover-bg)',
                'card-entry-txt': 'var(--card-entry-txt)',
                'card-entry-icon': 'var(--card-entry-icon)',
                'card-entry-icon-hover': 'var(--card-entry-icon-hover)',

                'panel-bg': 'var(--panel-bg)',
                'panel-txt': 'var(--panel-txt)',
                'panel-border': 'var(--panel-border)',

                'dropdown-item-hover-bg': 'var(--dropdown-item-hover-bg)',
                'dropdown-header-border': 'var(--dropdown-header-border)',

                'dialog-scrim': 'var(--dialog-scrim)',
                'dialog-title-txt': 'var(--dialog-title-txt)',
                'dialog-text-txt': 'var(--dialog-text-txt)',
                'dialog-icon': 'var(--dialog-icon)',
                'dialog-danger-icon': 'var(--dialog-danger-icon)',
                'dialog-actions-bg': 'var(--dialog-actions-bg)',
                'dialog-actions-border': 'var(--dialog-actions-border)',
                'dialog-cancel-bg': 'var(--dialog-cancel-bg)',
                'dialog-cancel-txt': 'var(--dialog-cancel-txt)',
                'dialog-cancel-hover-bg': 'var(--dialog-cancel-hover-bg)',
                'dialog-confirm-bg': 'var(--dialog-confirm-bg)',
                'dialog-confirm-hover-bg': 'var(--dialog-confirm-hover-bg)',
                'dialog-confirm-txt': 'var(--dialog-confirm-txt)',
                'dialog-danger-confirm-bg': 'var(--dialog-danger-confirm-bg)',

                'drawer-scrim': 'var(--drawer-scrim)',

                'field-bg': 'var(--field-bg)',
                'field-emphasis-txt': 'var(--field-emphasis-txt)',
                'field-placeholder-txt': 'var(--field-placeholder-txt)',
                'field-focus-border': 'var(--field-focus-border)',
                'field-ring-offset': 'var(--field-ring-offset)',
                'field-disabled-bg': 'var(--field-disabled-bg)',
                'field-icon': 'var(--field-icon)',
                'field-legend-txt': 'var(--field-legend-txt)',
                'check-bg': 'var(--check-bg)',
                'check-border': 'var(--check-border)',
                'check-fill': 'var(--check-fill)',
                'file-button-bg': 'var(--file-button-bg)',
                'file-button-txt': 'var(--file-button-txt)',
                'file-button-border': 'var(--file-button-border)',
                'file-button-hover-bg': 'var(--file-button-hover-bg)',

                // Segment (the on/off pair a radio group is drawn as). Named apart from the
                // toggle below because they are two components, not one: this is a row of choices
                // where one is chosen, the switch is one control with two states.
                'segment-selected-bg': 'var(--segment-selected-bg)',
                'segment-selected-txt': 'var(--segment-selected-txt)',

                'select-chip-bg': 'var(--select-chip-bg)',
                'select-chip-txt': 'var(--select-chip-txt)',
                'select-clear-txt': 'var(--select-clear-txt)',
                'select-clear-hover-txt': 'var(--select-clear-hover-txt)',
                'select-overflow-txt': 'var(--select-overflow-txt)',
                'select-tray-border': 'var(--select-tray-border)',
                'select-joined-edge': 'var(--select-joined-edge)',
                'select-waiting-txt': 'var(--select-waiting-txt)',
                'select-message-txt': 'var(--select-message-txt)',
                'select-retry-txt': 'var(--select-retry-txt)',

                'select-option-selected-bg': 'var(--select-option-selected-bg)',
                'select-option-highlight-bg': 'var(--select-option-highlight-bg)',
                'select-option-selected-txt': 'var(--select-option-selected-txt)',
                'select-option-highlight-txt': 'var(--select-option-highlight-txt)',
                'select-option-desc-txt': 'var(--select-option-desc-txt)',
                'select-option-desc-selected-txt': 'var(--select-option-desc-selected-txt)',
                'select-option-disabled-txt': 'var(--select-option-disabled-txt)',
                'select-group-txt': 'var(--select-group-txt)',

                // Date panel
                'date-cell-hover-bg': 'var(--date-cell-hover-bg)',
                'date-cell-hover-txt': 'var(--date-cell-hover-txt)',
                'date-cell-selected-bg': 'var(--date-cell-selected-bg)',
                'date-cell-selected-txt': 'var(--date-cell-selected-txt)',
                'date-cell-weekno-txt': 'var(--date-cell-weekno-txt)',
                // The designer confirmed the weekend marking and the warning colour are the same
                // colour, not two that happen to coincide — so this rung moves when warning does.
                'date-cell-weekend-txt': 'var(--date-cell-weekend-txt)',

                'badge-txt': 'var(--badge-txt)',
                'badge-count-bg': 'var(--badge-count-bg)',
                'badge-success': 'var(--badge-success)',
                'badge-warning': 'var(--badge-warning)',
                'badge-danger': 'var(--badge-danger)',
                'badge-info': 'var(--badge-info)',
                'badge-neutral': 'var(--badge-neutral)',

                'button-primary-bg': 'var(--button-primary-bg)',
                'button-primary-hover-bg': 'var(--button-primary-hover-bg)',
                'button-primary-txt': 'var(--button-primary-txt)',
                'button-outline-bg': 'var(--button-outline-bg)',
                'button-outline-txt': 'var(--button-outline-txt)',
                'button-outline-border': 'var(--button-outline-border)',
                'button-outline-hover-bg': 'var(--button-outline-hover-bg)',
                'button-danger-txt': 'var(--button-danger-txt)',
                'button-danger-border': 'var(--button-danger-border)',
                'button-danger-hover-bg': 'var(--button-danger-hover-bg)',
                'button-ghost-hover-bg': 'var(--button-ghost-hover-bg)',

                'loader-overlay-bg': 'var(--loader-overlay-bg)',
                'loader-track': 'var(--loader-track)',
                'loader-ball': 'var(--loader-ball)',
                'loader-spinner': 'var(--loader-spinner)',
                'loader-error': 'var(--loader-error)',

                // Table (FA)
                'table-border': 'var(--table-border)',
                'table-row-odd-bg': 'var(--table-row-odd-bg)',
                'table-row-even-bg': 'var(--table-row-even-bg)',

                // Data-row status (FA)
                'row-settled-bg': 'var(--row-settled-bg)',
                'row-settled-txt': 'var(--row-settled-txt)',
                'row-inquiry-bg': 'var(--row-inquiry-bg)',
                'row-overdue-bg': 'var(--row-overdue-bg)',
                'row-overdue-txt': 'var(--row-overdue-txt)',
                'row-inactive-txt': 'var(--row-inactive-txt)',
                'row-label-bg': 'var(--row-label-bg)',

                // Tabs (FA)
                'tab-border': 'var(--tab-border)',
                'tab-hover-bg': 'var(--tab-hover-bg)',
                'tab-rule': 'var(--tab-rule)',
                'tab-txt': 'var(--tab-txt)',
                'tab-current-bg': 'var(--tab-current-bg)',
                'tab-current-txt': 'var(--tab-current-txt)',

                // Messages (FA)
                'message-error-bg': 'var(--message-error-bg)',
                'message-error-border': 'var(--message-error-border)',
                'message-error-txt': 'var(--message-error-txt)',
                'message-warning-bg': 'var(--message-warning-bg)',
                'message-warning-border': 'var(--message-warning-border)',
                'message-warning-txt': 'var(--message-warning-txt)',
                'message-note-bg': 'var(--message-note-bg)',
                'message-note-border': 'var(--message-note-border)',
                'message-note-txt': 'var(--message-note-txt)',

                // Backtrace (FA) — the debug call stack under a message
                'backtrace-frame-border': 'var(--backtrace-frame-border)',
                'backtrace-frame-bg': 'var(--backtrace-frame-bg)',
                'backtrace-index-txt': 'var(--backtrace-index-txt)',
                'backtrace-path-txt': 'var(--backtrace-path-txt)',
                'backtrace-file-txt': 'var(--backtrace-file-txt)',
                'backtrace-line-txt': 'var(--backtrace-line-txt)',
                'backtrace-call-txt': 'var(--backtrace-call-txt)',

                'banner-brand-bg': 'var(--banner-brand-bg)',
                'banner-brand-txt': 'var(--banner-brand-txt)',
                'banner-success-bg': 'var(--banner-success-bg)',
                'banner-success-border': 'var(--banner-success-border)',
                'banner-success-txt': 'var(--banner-success-txt)',
                'banner-success-close-hover-txt': 'var(--banner-success-close-hover-txt)',
                'banner-warning-bg': 'var(--banner-warning-bg)',
                'banner-warning-border': 'var(--banner-warning-border)',
                'banner-warning-txt': 'var(--banner-warning-txt)',
                'banner-error-bg': 'var(--banner-error-bg)',
                'banner-error-border': 'var(--banner-error-border)',
                'banner-error-txt': 'var(--banner-error-txt)',
                'banner-error-close-hover-txt': 'var(--banner-error-close-hover-txt)',

                'link-txt': 'var(--link-txt)',
                'link-utility-txt': 'var(--link-utility-txt)',

                'toggle-flush': 'var(--toggle-flush)',
                'toggle-txt': 'var(--toggle-txt)',
                'toggle-border': 'var(--toggle-border)',
                'toggle-knob': 'var(--toggle-knob)',
                'toggle-on-flush': 'var(--toggle-on-flush)',
                'toggle-on-txt': 'var(--toggle-on-txt)',
                'toggle-on-border': 'var(--toggle-on-border)',
                'toggle-on-knob': 'var(--toggle-on-knob)',
                'toggle-wash-txt': 'var(--toggle-wash-txt)',
                'toggle-primary-flush': 'var(--toggle-primary-flush)',
                'toggle-primary-mark': 'var(--toggle-primary-mark)',
                'toggle-success-flush': 'var(--toggle-success-flush)',
                'toggle-success-mark': 'var(--toggle-success-mark)',
                'toggle-warning-flush': 'var(--toggle-warning-flush)',
                'toggle-warning-mark': 'var(--toggle-warning-mark)',
                'toggle-danger-flush': 'var(--toggle-danger-flush)',
                'toggle-danger-mark': 'var(--toggle-danger-mark)',
                'toggle-neutral-flush': 'var(--toggle-neutral-flush)',
                'toggle-neutral-mark': 'var(--toggle-neutral-mark)',
                'toggle-disabled-flush': 'var(--toggle-disabled-flush)',
                'toggle-disabled-txt': 'var(--toggle-disabled-txt)',
                'toggle-disabled-border': 'var(--toggle-disabled-border)',
                'toggle-disabled-knob': 'var(--toggle-disabled-knob)',
            },
            width: {
                sidebar: '280px',
            },
            height: {
                header: '60px',
                footer: '30px',
            },
        },
    },
};
