<?php
/**********************************************************************
    Copyright (C) FrontAccounting, LLC.
	Released under the terms of the GNU General Public License, GPL, 
	as published by the Free Software Foundation, either version 3 
	of the License, or (at your option) any later version.
    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  
    See the License here <http://www.gnu.org/licenses/gpl-3.0.html>.
***********************************************************************/
require_once __DIR__ . "/../../includes/db/manufacturing_db.inc";
require_once __DIR__ . "/../../manufacturing/includes/db/work_centres_db.inc";
require_once __DIR__ . "/../../manufacturing/includes/db/work_orders_db.inc";
require_once __DIR__ . "/../../manufacturing/includes/db/work_order_costing_db.inc";
require_once __DIR__ . "/../../manufacturing/includes/db/work_order_issues_db.inc";
require_once __DIR__ . "/../../manufacturing/includes/db/work_order_produce_items_db.inc";
require_once __DIR__ . "/../../manufacturing/includes/db/work_order_requirements_db.inc";

