'use strict';

const icons = {
    add: 'icon-plus-circle',
    alloc: 'icon-alloc',
    button_ok: 'icon-button-ok',
    cal: 'icon-cal',
    cancel: 'icon-block-flipped',
    closed: 'icon-lock',
    credit: 'icon-credit',
    delete: 'icon-delete',
    download: 'icon-download',
    edit: 'icon-pencil',
    escape: 'icon-cancel',
    gl: 'icon-gl',
    help: 'icon-help-outline',
    invoice: 'icon-invoice',
    locate: 'icon-search',
    lock: 'icon-lock',
    log: 'icon-log',
    login: 'icon-logout',
    money: 'icon-banknote',
    ok: 'icon-button-ok',
    pdf: 'icon-file-pdf',
    preferences: 'icon-prefs',
    print: 'icon-print',
    receive: 'icon-receive',
    remove: 'icon-minus-outline',
    report: 'icon-reports',
    right: 'icon-deliver',
    sort_asc: 'icon-sort-asc',
    sort_desc: 'icon-sort-desc',
    sort_none: 'icon-sort-none',
    spacer: 'icon-spacer',
    view: 'icon-view',
    warning: 'icon-warning',
};

export default icons;
